final List<String> foodProducts = [
  "Salt",
  "Pepper",
  "Olive Oil",
  "Garlic",
  "Onion",
  "Butter",
  "Flour",
  "Sugar",
  "Eggs",
  "Milk",
  "Cream",
  "Cheese",
  "Tomatoes",
  "Potatoes",
  "Carrots",
  "Broccoli",
  "Spinach",
  "Lettuce",
  "Cucumbers",
  "Bell Peppers",
  "Chicken",
  "Beef",
  "Pork",
  "Fish",
  "Shrimp",
  "Lobster",
  "Crab",
  "Rice",
  "Pasta",
  "Bread",
  "Cornmeal",
  "Oats",
  "Honey",
  "Vinegar",
  "Soy Sauce",
  "Worcestershire Sauce",
  "Mustard",
  "Ketchup",
  "Mayonnaise",
  "Sour Cream",
  "Yogurt",
  "Nuts",
  "Seeds",
  "Herbs",
  "Spices",
  "Cinnamon",
  "Nutmeg",
  "Paprika",
  "Cumin",
  "Thyme",
  "Rosemary",
  "Basil",
  "Oregano",
  "Bay Leaves",
  "Sage",
  "Chives",
  "Lemon",
  "Lime",
  "Orange",
  "Grapefruit",
  "Apples",
  "Bananas",
  "Strawberries",
  "Blueberries",
  "Raspberries",
  "Blackberries",
  "Peaches",
  "Plums",
  "Pineapple",
  "Mango",
  "Avocado",
  "Coconut",
  "Chocolate",
  "Cocoa Powder",
  "Vanilla Extract",
  "Baking Powder",
  "Baking Soda",
  "Yeast",
  "Cornstarch",
  "Gelatin",
  "Condensed Milk",
  "Evaporated Milk",
  "Coconut Milk",
  "Broth",
  "Stock",
  "Canned Tomatoes",
  "Canned Beans",
  "Canned Corn",
  "Frozen Vegetables",
  "Frozen Fruit",
  "Bouillon Cubes"
  "Anchovies",
  "Artichokes",
  "Asparagus",
  "Avocado",
  "Bacon",
  "Basil",
  "Bay leaves",
  "Beans",
  "Beets",
  "Bell peppers",
  "Black beans",
  "Black olives",
  "Broccoli",
  "Brown rice",
  "Brussels sprouts",
  "Buckwheat",
  "Butter",
  "Buttermilk",
  "Cabbage",
  "Camembert cheese",
  "Capers",
  "Carrots",
  "Cashews",
  "Cauliflower",
  "Cayenne pepper",
  "Celery",
  "Cheddar cheese",
  "Chickpeas",
  "Chives",
  "Cilantro",
  "Cinnamon",
  "Cloves",
  "Coconut",
  "Coconut milk",
  "Cod",
  "Collard greens",
  "Coriander",
  "Corn",
  "Cornmeal",
  "Cottage cheese",
  "Cranberries",
  "Cream",
  "Cucumber",
  "Cumin",
  "Curry powder",
  "Dill",
  "Edamame",
  "Eggplant",
  "Eggs",
  "Endive",
  "Fennel",
  "Feta cheese",
  "Flaxseed",
  "Flour",
  "Fontina cheese",
  "French bread",
  "Garlic",
  "Ginger",
  "Goat cheese",
  "Grapefruit",
  "Grapes",
  "Greek yogurt",
  "Green beans",
  "Green olives",
  "Green onions",
  "Gruyere cheese",
  "Halibut",
  "Harissa",
  "Hazelnuts",
  "Honey",
  "Horseradish",
  "Jalapenos",
  "Jasmine rice",
  "Kale",
  "Ketchup",
  "Kidney beans",
  "Kimchi",
  "Kiwi",
  "Kohlrabi",
  "Lamb",
  "Leeks",
  "Lemon",
  "Lentils",
  "Lettuce",
  "Lime",
  "Linguine",
  "Lobster",
  "Macadamia nuts",
  "Mango",
  "Maple syrup",
  "Mascarpone cheese",
  "Millet",
  "Mint",
  "Miso",
  "Monterey Jack cheese",
  "Mozzarella cheese",
  "Mushrooms",
  "Mustard",
  "Napa cabbage",
  "Navy beans",
  "Asparagus",
  "Barley",
  "Basil",
  "Black beans",
  "Broccoli",
  "Brussels sprouts",
  "Butternut squash",
  "Cabbage",
  "Cantaloupe",
  "Carrots",
  "Cashews",
  "Cauliflower",
  "Celery",
  "Chia seeds",
  "Chickpeas",
  "Chives",
  "Cilantro",
  "Cinnamon",
  "Coconut milk",
  "Collard greens",
  "Coriander",
  "Cornmeal",
  "Cottage cheese",
  "Cranberries",
  "Cumin",
  "Dijon mustard",
  "Dill",
  "Edamame",
  "Eggplant",
  "Fennel",
  "Flaxseed",
  "Garlic powder",
  "Ginger",
  "Gouda cheese",
  "Grapefruit",
  "Green beans",
  "Green lentils",
  "Hazelnuts",
  "Honey",
  "Horseradish",
  "Jalapeno peppers",
  "Kale",
  "Kidney beans",
  "Lavender",
  "Leeks",
  "Lemon juice",
  "Lime juice",
  "Mango",
  "Maple syrup",
  "Marjoram",
  "Mascarpone cheese",
  "Millet",
  "Miso",
  "Molasses",
  "Mushrooms",
  "Mustard greens",
  "Nectarines",
  "Nutmeg",
  "Oat milk",
  "Oregano",
  "Paprika",
  "Parsley",
  "Pecans",
  "Pine nuts",
  "Pistachios",
  "Plums",
  "Pomegranate",
  "Poppy seeds",
  "Portobello mushrooms",
  "Provolone cheese",
  "Quinoa",
  "Radishes",
  "Raisins",
  "Red bell peppers",
  "Rhubarb",
  "Ricotta cheese",
  "Rosemary",
  "Saffron",
  "Sage",
  "Scallions",
  "Sesame oil",
  "Shallots",
  "Soy sauce",
  "Spinach",
  "Sunflower seeds",
  "Sweet potatoes",
  "Tarragon",
  "Thyme",
  "Tofu",
  "Turmeric",
  "Vanilla extract",
  "Walnuts",
  "Watercress",
  "Yams",
  "Yellow squash",
  "Zucchini"
];