final List<String> foodProducts = [
  "Salt",
  "Pepper",
  "Olive Oil",
  "Garlic",
  "Onion",
  "Butter",
  "Flour",
  "Sugar",
  "Eggs",
  "Milk",
  "Cream",
  "Cheese",
  "Tomatoes",
  "Potatoes",
  "Carrots",
  "Broccoli",
  "Spinach",
  "Lettuce",
  "Cucumbers",
  "Bell Peppers",
  "Chicken",
  "Beef",
  "Pork",
  "Fish",
  "Shrimp",
  "Lobster",
  "Crab",
  "Rice",
  "Pasta",
  "Bread",
  "Cornmeal",
  "Oats",
  "Honey",
  "Vinegar",
  "Soy Sauce",
  "Worcestershire Sauce",
  "Mustard",
  "Ketchup",
  "Mayonnaise",
  "Sour Cream",
  "Yogurt",
  "Nuts",
  "Seeds",
  "Herbs",
  "Spices",
  "Cinnamon",
  "Nutmeg",
  "Paprika",
  "Cumin",
  "Thyme",
  "Rosemary",
  "Basil",
  "Oregano",
  "Bay Leaves",
  "Sage",
  "Chives",
  "Lemon",
  "Lime",
  "Orange",
  "Grapefruit",
  "Apples",
  "Bananas",
  "Strawberries",
  "Blueberries",
  "Raspberries",
  "Blackberries",
  "Peaches",
  "Plums",
  "Pineapple",
  "Mango",
  "Avocado",
  "Coconut",
  "Chocolate",
  "Cocoa Powder",
  "Vanilla Extract",
  "Baking Powder",
  "Baking Soda",
  "Yeast",
  "Cornstarch",
  "Gelatin",
  "Condensed Milk",
  "Evaporated Milk",
  "Coconut Milk",
  "Broth",
  "Stock",
  "Canned Tomatoes",
  "Canned Beans",
  "Canned Corn",
  "Frozen Vegetables",
  "Frozen Fruit",
  "Bouillon Cubes"
  "Anchovies",
  "Artichokes",
  "Asparagus",
  "Bacon",
  "Bay leaves",
  "Beans",
  "Beets",
  "Bell peppers",
  "Black beans",
  "Black olives",
  "Brown rice",
  "Brussels sprouts",
  "Buckwheat",
  "Buttermilk",
  "Cabbage",
  "Camembert cheese",
  "Capers",
  "Cashews",
  "Cauliflower",
  "Cayenne pepper",
  "Celery",
  "Cheddar cheese",
  "Chickpeas",
  "Cilantro",
  "Cloves",
  "Coconut milk",
  "Cod",
  "Collard greens",
  "Coriander",
  "Corn",
  "Cottage cheese",
  "Cranberries",
  "Cucumber",
  "Curry powder",
  "Dill",
  "Edamame",
  "Eggplant",
  "Endive",
  "Fennel",
  "Feta cheese",
  "Flaxseed",
  "Fontina cheese",
  "French bread",
  "Ginger",
  "Goat cheese",
  "Grapes",
  "Greek yogurt",
  "Green beans",
  "Green olives",
  "Green onions",
  "Gruyere cheese",
  "Halibut",
  "Harissa",
  "Hazelnuts",
  "Horseradish",
  "Jalapenos",
  "Jasmine rice",
  "Kale",
  "Kidney beans",
  "Kimchi",
  "Kiwi",
  "Kohlrabi",
  "Lamb",
  "Leeks",
  "Lentils",
  "Linguine",
  "Macadamia nuts",
  "Maple syrup",
  "Mascarpone cheese",
  "Millet",
  "Mint",
  "Miso",
  "Monterey Jack cheese",
  "Mozzarella cheese",
  "Mushrooms",
  "Napa cabbage",
  "Navy beans",
  "Barley",
  "Butternut squash",
  "Cantaloupe",
  "Chia seeds",
  "Dijon mustard",
  "Garlic powder",
  "Gouda cheese",
  "Green lentils",
  "Jalapeno peppers",
  "Lavender",
  "Lemon juice",
  "Lime juice",
  "Marjoram",
  "Molasses",
  "Mustard greens",
  "Nectarines",
  "Oat milk",
  "Parsley",
  "Pecans",
  "Pine nuts",
  "Pistachios",
  "Pomegranate",
  "Poppy seeds",
  "Portobello mushrooms",
  "Provolone cheese",
  "Quinoa",
  "Radishes",
  "Raisins",
  "Red bell peppers",
  "Rhubarb",
  "Ricotta cheese",
  "Saffron",
  "Scallions",
  "Sesame oil",
  "Shallots",
  "Soy sauce",
  "Sunflower seeds",
  "Sweet potatoes",
  "Tarragon",
  "Tofu",
  "Turmeric",
  "Vanilla extract",
  "Walnuts",
  "Watercress",
  "Yams",
  "Yellow squash",
  "Zucchini"
];

final List<String> foodProductsSv = [
  "Salt",
  "Peppar",
  "Olivolja",
  "Vitlök",
  "Lök",
  "Smör",
  "Mjöl",
  "Socke",
  "Ägg",
  "Mjölk",
  "Grädde",
  "Ost",
  "Tomater",
  "Potatis",
  "Morötter",
  "Broccoli",
  "Spenat",
  "Sallad",
  "Gurka",
  "Paprika",
  "Kyckling",
  "Nötkött",
  "Fläskkött",
  "Fisk",
  "Räkor",
  "Hummer",
  "Kräftor",
  "Ris",
  "Pasta",
  "Bröd",
  "Majsmjöl",
  "Havregryn",
  "Honung",
  "Vinäger",
  "Sojasås",
  "Worcestershiresås",
  "Senap",
  "Ketchup",
  "Majonnäs",
  "Sour Cream",
  "Yoghurt",
  "Nötter",
  "Frön",
  "Örter",
  "Kryddor",
  "Kanel",
  "Muskotnöt",
  "Paprika",
  "Kummin",
  "Timjan",
  "Rosmarin",
  "Basilika",
  "Oregano",
  "Lagerblad",
  "Salvia",
  "Salladslök",
  "Citron",
  "Lime",
  "Apelsin",
  "Grapefrukt",
  "Äpplen",
  "Bananer",
  "Jordgubbar",
  "Blåbär",
  "Hallon",
  "Svarta vinbär",
  "Persikor",
  "Plommon",
  "Ananas",
  "Mango",
  "Avokado",
  "Kokos",
  "Choklad",
  "Kakaopulver",
  "Vaniljextrakt",
  "Bakpulver",
  "Bikarbonat",
  "Jäst",
  "Majsstärkelse",
  "Gelatin",
  "Koncentrerad mjölk",
  "Kondenserad mjölk",
  "Kokosmjölk",
  "Buljong",
  "Fond",
  "Konserverade tomater",
  "Konserverade bönor",
  "Konserverad majs",
  "Frysta grönsaker",
  "Fryst frukt",
  "Buljongtärningar",
  "Ansjovis",
  "Kronärtskockor",
  "Sparris",
  "Bacon",
  "Lagerblad",
  "Bönor",
  "Rödbetor",
  "Paprika",
  "Svarta bönor",
  "Svarta oliver",
  "Brun ris",
  "Brysselkål",
  "BoVete",
  "Kärnmjölk",
  "Kål",
  "Camembertost",
  "Kapris",
  "Cashewnötter",
  "Blomkål",
  "Cayennepeppar",
  "Selleri",
  "Cheddarost",
  "Kikärter",
  "Koriander",
  "Kryddnejlikor",
  "Kokosmjölk",
  "Torsk",
  "Grönkål",
  "Koriander",
  "Majs",
  "Keso",
  "Tranbär",
  "Gurka",
  "Currypulver",
  "Dill",
  "Edamame",
  "Aubergine",
  "Cikoria",
  "Fänkål",
  "Fetaost",
  "Linfrö",
  "Fontinaost",
  "Franskt bröd",
  "Ingefära",
  "Getost",
  "Druvor",
  "Grekisk yoghurt",
  "Gröna bönor",
  "Gröna oliver",
  "Gröna lökar",
  "Gruyèreost",
  "Hälleflundra",
  "Harissa",
  "Hasselnötter",
  "Pepparrot",
  "Jalapeños",
  "Jasminris",
  "Grönkål",
  "Kidneybönor",
  "Kimchi",
  "Kiwi",
  "Kålrabi",
  "Lamm",
  "Purjolök",
  "Linser",
  "Linguine",
  "Macadamianötter",
  "Lönnsirap",
  "Mascarponeost",
  "Hirs",
  "Mynta",
  "Miso",
  "Monterey Jack-ost",
  "Mozzarellaost",
  "Champinjoner",
  "Napa-kål",
  "Marinbönor",
  "Korn",
  "Butternut-squash",
  "Cantaloupe",
  "Chiafrön",
  "Dijonsenap",
  "Vitlökspulver",
  "Goudaost",
  "Gröna linser",
  "Jalapeñopeppar",
  "Lavendel",
  "Citronsaft",
  "Limejuice",
  "Malet mejram",
  "Molasses",
  "Senapsgrönsaker",
  "Nektariner",
  "Havremjölk",
  "Persilja",
  "Pekannötter",
  "Pinjenötter",
  "Pistachionötter",
  "Granatäpple",
  "Vallmofrön",
  "Portobello-svampar",
  "Provoloneost",
  "Quinoa",
  "Rädisor",
  "Russin",
  "Röda paprikor",
  "Rabarber",
  "Ricottaost",
  "Saffran",
  "Salladslök",
  "Sesamolja",
  "Scharlottenlök",
  "Sojasås",
  "Solrosfrön",
  "Sötpotatis",
  "Dragon",
  "Tofu",
  "Gurkmeja",
  "Vaniljextrakt",
  "Valnötter",
  "Krasse",
  "Yams",
  "Gul squash",
  "Zucchini"
];